# Generated by Django 6.0.6 on 2026-07-30 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("resumes", "0004_remove_old_date_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("website", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, upload_to="employer_logos/")),
                ("is_verified", models.BooleanField(default=False)),
                ("trust_score", models.IntegerField(default=0)),
                ("verification_details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "registered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employer",
                "ordering": ["-trust_score", "company_name"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("requirements", models.TextField(blank=True)),
                ("responsibilities", models.TextField(blank=True)),
                ("location", models.CharField(max_length=200)),
                ("is_remote", models.BooleanField(default=False)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full-Time"),
                            ("part_time", "Part-Time"),
                            ("contract", "Contract"),
                            ("temporary", "Temporary"),
                            ("internship", "Internship"),
                            ("freelance", "Freelance"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "application_url",
                    models.URLField(
                        blank=True,
                        help_text="External URL to apply (hidden behind paywall)",
                    ),
                ),
                (
                    "application_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email to send application (hidden behind paywall)",
                        max_length=254,
                    ),
                ),
                (
                    "application_instructions",
                    models.TextField(blank=True, help_text="Hidden behind paywall"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("employer", "Employer Posted"),
                            ("aggregated", "Aggregated"),
                            ("admin", "Admin Added"),
                        ],
                        default="employer",
                        max_length=20,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(blank=True, help_text="Original URL if aggregated"),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="External ID from source API",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "trust_score",
                    models.IntegerField(
                        default=0, help_text="0-100 score for scam detection"
                    ),
                ),
                ("verification_details", models.JSONField(blank=True, default=dict)),
                ("rejection_reason", models.TextField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requires_resume", models.BooleanField(default=True)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="jobs.employer",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-trust_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.job",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resumes.resume",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["location"], name="jobs_job_locatio_8b2f8c_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["category"], name="jobs_job_categor_653d6e_idx"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "trust_score"], name="jobs_job_status_cfd7ff_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobapplication",
            unique_together={("user", "job")},
        ),
    ]
