# Generated by Django 6.0.6 on 2026-07-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_alter_job_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="description_language",
            field=models.CharField(
                blank=True,
                help_text="Detected language code of original",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="description_original",
            field=models.TextField(
                blank=True, help_text="Original untranslated description"
            ),
        ),
    ]
