# Generated by Django 6.0.6 on 2026-07-31 04:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_description_language_job_description_original"),
    ]

    operations = [
        migrations.CreateModel(
            name="AggregationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("last_run", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Aggregation State",
                "verbose_name_plural": "Aggregation States",
            },
        ),
    ]
