from datetime import timedelta

from django.db import migrations
from django.utils import timezone


SAMPLE_JOBS = [
    {
        "employer": "Acme Corporation",
        "title": "Senior Backend Developer",
        "description": "Join a fast-growing SaaS team building high-scale APIs with Python and Django. You will design and ship features that serve millions of requests daily.",
        "requirements": "5+ years building backend services with Python/Django. Strong PostgreSQL and Redis skills. Experience with Docker and cloud deployments.",
        "responsibilities": "Design REST APIs, improve database performance, review pull requests, and mentor junior engineers.",
        "location": "Nairobi",
        "is_remote": True,
        "salary_min": 6000,
        "salary_max": 9000,
        "currency": "USD",
        "employment_type": "full_time",
        "category": "Engineering",
        "trust_score": 92,
        "days_ago": 1,
    },
    {
        "employer": "Acme Corporation",
        "title": "Product Designer",
        "description": "Craft intuitive, beautiful interfaces for a B2B analytics platform. Own the design process from research to high-fidelity mockups.",
        "requirements": "Portfolio showing end-to-end product design work. Proficiency in Figma and prototyping tools.",
        "responsibilities": "Lead UX research, design user flows, maintain the design system, and partner with engineering to ship polished UI.",
        "location": "Remote (Global)",
        "is_remote": True,
        "salary_min": 4500,
        "salary_max": 6500,
        "currency": "USD",
        "employment_type": "full_time",
        "category": "Design",
        "trust_score": 90,
        "days_ago": 2,
    },
    {
        "employer": "Globex Industries",
        "title": "Data Analyst",
        "description": "Turn raw data into actionable insights for supply chain operations. Build dashboards and reports used by leadership.",
        "requirements": "Strong SQL and Excel skills. Experience with Power BI or Tableau is a plus.",
        "responsibilities": "Maintain data pipelines, create weekly performance dashboards, and present findings to stakeholders.",
        "location": "Kampala",
        "is_remote": False,
        "salary_min": 3500,
        "salary_max": 5000,
        "currency": "USD",
        "employment_type": "full_time",
        "category": "Data",
        "trust_score": 85,
        "days_ago": 3,
    },
    {
        "employer": "Globex Industries",
        "title": "Logistics Coordinator",
        "description": "Coordinate shipments across East Africa and ensure on-time delivery. You will work closely with carriers and warehouse teams.",
        "requirements": "2+ years in logistics or supply chain. Strong organizational and communication skills.",
        "responsibilities": "Schedule shipments, track deliveries, resolve delays, and maintain shipping documentation.",
        "location": "Kampala",
        "is_remote": False,
        "salary_min": 2500,
        "salary_max": 3500,
        "currency": "USD",
        "employment_type": "full_time",
        "category": "Operations",
        "trust_score": 80,
        "days_ago": 5,
    },
    {
        "employer": "Initech Solutions",
        "title": "Frontend Developer",
        "description": "Build modern web applications with React and TypeScript. Work on a design system used across multiple products.",
        "requirements": "3+ years with React, TypeScript, and modern CSS. Understanding of accessibility best practices.",
        "responsibilities": "Implement UI components, optimize page performance, and collaborate with designers on new features.",
        "location": "Lagos",
        "is_remote": True,
        "salary_min": 4000,
        "salary_max": 6000,
        "currency": "USD",
        "employment_type": "full_time",
        "category": "Engineering",
        "trust_score": 88,
        "days_ago": 1,
    },
    {
        "employer": "Initech Solutions",
        "title": "DevOps Engineer",
        "description": "Own the infrastructure that powers a high-traffic fintech platform. Automate deployments and improve reliability.",
        "requirements": "Experience with AWS or GCP, Terraform, Kubernetes, and CI/CD pipelines.",
        "responsibilities": "Build and maintain cloud infrastructure, implement monitoring and alerting, and optimize costs.",
        "location": "Lagos",
        "is_remote": True,
        "salary_min": 5500,
        "salary_max": 8000,
        "currency": "USD",
        "employment_type": "full_time",
        "category": "Engineering",
        "trust_score": 87,
        "days_ago": 4,
    },
    {
        "employer": "Umbrella Health",
        "title": "Registered Nurse",
        "description": "Provide compassionate patient care at a leading private hospital. Work with a supportive team of healthcare professionals.",
        "requirements": "Valid nursing license. Degree in Nursing and 2+ years of clinical experience.",
        "responsibilities": "Administer medication, monitor patient vitals, maintain records, and support families.",
        "location": "Kigali",
        "is_remote": False,
        "salary_min": 3000,
        "salary_max": 4500,
        "currency": "USD",
        "employment_type": "full_time",
        "category": "Healthcare",
        "trust_score": 90,
        "days_ago": 2,
    },
    {
        "employer": "Umbrella Health",
        "title": "Public Health Officer",
        "description": "Support community health programs and outreach initiatives. Analyze health data and coordinate field teams.",
        "requirements": "Degree in public health or related field. Strong analytical and reporting skills.",
        "responsibilities": "Plan outreach campaigns, train field staff, and prepare program reports.",
        "location": "Kigali",
        "is_remote": False,
        "salary_min": 2800,
        "salary_max": 4000,
        "currency": "USD",
        "employment_type": "contract",
        "category": "Healthcare",
        "trust_score": 82,
        "days_ago": 6,
    },
    {
        "employer": "Stark Digital",
        "title": "Marketing Manager",
        "description": "Lead growth marketing for a D2C e-commerce brand. Own paid channels, email campaigns, and brand partnerships.",
        "requirements": "5+ years in digital marketing. Proven track record scaling acquisition with measurable ROI.",
        "responsibilities": "Own the marketing budget, run multi-channel campaigns, and report on growth metrics.",
        "location": "Nairobi",
        "is_remote": False,
        "salary_min": 5000,
        "salary_max": 7000,
        "currency": "USD",
        "employment_type": "full_time",
        "category": "Marketing",
        "trust_score": 89,
        "days_ago": 1,
    },
    {
        "employer": "Stark Digital",
        "title": "Content Writer",
        "description": "Produce SEO-optimized articles and product copy that convert. Write across blogs, email, and social channels.",
        "requirements": "Strong portfolio of published writing. Understanding of SEO fundamentals.",
        "responsibilities": "Research topics, write and edit content, and collaborate with the SEO team.",
        "location": "Remote (Global)",
        "is_remote": True,
        "salary_min": 1800,
        "salary_max": 3000,
        "currency": "USD",
        "employment_type": "freelance",
        "category": "Marketing",
        "trust_score": 84,
        "days_ago": 3,
    },
    {
        "employer": "Wayne Enterprises",
        "title": "Financial Analyst",
        "description": "Analyze financial performance and support strategic planning for a diversified group of companies.",
        "requirements": "Degree in finance or accounting. CFA progress or MBA is an advantage. Strong Excel and financial modeling skills.",
        "responsibilities": "Build financial models, prepare board reports, and support budgeting and forecasting.",
        "location": "Johannesburg",
        "is_remote": False,
        "salary_min": 6000,
        "salary_max": 8500,
        "currency": "USD",
        "employment_type": "full_time",
        "category": "Finance",
        "trust_score": 91,
        "days_ago": 4,
    },
    {
        "employer": "Wayne Enterprises",
        "title": "Legal Counsel",
        "description": "Provide legal guidance on contracts, compliance, and corporate governance for a growing multinational.",
        "requirements": "LLB degree and admission to the bar. 4+ years of corporate or commercial law experience.",
        "responsibilities": "Draft and review contracts, advise on regulatory compliance, and manage legal risk.",
        "location": "Johannesburg",
        "is_remote": False,
        "salary_min": 8000,
        "salary_max": 11000,
        "currency": "USD",
        "employment_type": "full_time",
        "category": "Legal",
        "trust_score": 88,
        "days_ago": 7,
    },
    {
        "employer": "Pied Piper",
        "title": "Full-Stack Engineer (Internship)",
        "description": "Hands-on internship building real features for a data-compression startup. Learn from senior engineers while shipping production code.",
        "requirements": "Working knowledge of Python and JavaScript. Currently enrolled in or recently graduated from a CS program.",
        "responsibilities": "Build features end-to-end, fix bugs, and participate in code reviews and team rituals.",
        "location": "Remote (Global)",
        "is_remote": True,
        "salary_min": 800,
        "salary_max": 1500,
        "currency": "USD",
        "employment_type": "internship",
        "category": "Engineering",
        "trust_score": 86,
        "days_ago": 2,
    },
    {
        "employer": "Pied Piper",
        "title": "QA Engineer",
        "description": "Ensure product quality through manual and automated testing. Champion test automation across teams.",
        "requirements": "Experience with Selenium, Playwright, or similar. Strong attention to detail.",
        "responsibilities": "Write automated test suites, perform regression testing, and report defects.",
        "location": "Remote (Global)",
        "is_remote": True,
        "salary_min": 3000,
        "salary_max": 4500,
        "currency": "USD",
        "employment_type": "full_time",
        "category": "Engineering",
        "trust_score": 83,
        "days_ago": 5,
    },
    {
        "employer": "Soylent Corp",
        "title": "Human Resources Manager",
        "description": "Lead HR operations for a 200-person company. Own recruitment, employee engagement, and performance management.",
        "requirements": "5+ years in HR management. Strong knowledge of local labor law.",
        "responsibilities": "Manage the hiring pipeline, run onboarding, resolve employee relations issues, and drive culture initiatives.",
        "location": "Nairobi",
        "is_remote": False,
        "salary_min": 4500,
        "salary_max": 6000,
        "currency": "USD",
        "employment_type": "full_time",
        "category": "Human Resources",
        "trust_score": 85,
        "days_ago": 6,
    },
    {
        "employer": "Soylent Corp",
        "title": "Customer Success Specialist",
        "description": "Be the voice of the customer. Help clients get the most out of our software and reduce churn.",
        "requirements": "1+ year in customer support or account management. Excellent written and verbal communication.",
        "responsibilities": "Onboard new customers, resolve tickets, and conduct periodic check-ins.",
        "location": "Accra",
        "is_remote": True,
        "salary_min": 2200,
        "salary_max": 3200,
        "currency": "USD",
        "employment_type": "full_time",
        "category": "Customer Service",
        "trust_score": 81,
        "days_ago": 2,
    },
    {
        "employer": "Hooli",
        "title": "Machine Learning Engineer",
        "description": "Build and deploy ML models that power recommendations and personalization for millions of users.",
        "requirements": "MS or PhD in ML/CS, or equivalent experience. Proficiency in PyTorch or TensorFlow and Python.",
        "responsibilities": "Train, evaluate, and deploy models. Collaborate with data engineers on pipelines.",
        "location": "Cape Town",
        "is_remote": True,
        "salary_min": 9000,
        "salary_max": 13000,
        "currency": "USD",
        "employment_type": "full_time",
        "category": "Data",
        "trust_score": 93,
        "days_ago": 1,
    },
    {
        "employer": "Hooli",
        "title": "Security Engineer",
        "description": "Protect user data and infrastructure. Run penetration tests, respond to incidents, and build security tooling.",
        "requirements": "Strong background in application security and cloud security. OSCP or equivalent is a plus.",
        "responsibilities": "Conduct security reviews, automate threat detection, and lead incident response.",
        "location": "Cape Town",
        "is_remote": True,
        "salary_min": 8500,
        "salary_max": 12000,
        "currency": "USD",
        "employment_type": "full_time",
        "category": "Engineering",
        "trust_score": 90,
        "days_ago": 3,
    },
]


def seed_sample_jobs(apps, schema_editor):
    Employer = apps.get_model('jobs', 'Employer')
    Job = apps.get_model('jobs', 'Job')
    now = timezone.now()
    for data in SAMPLE_JOBS:
        employer_name = data.pop('employer')
        employer, _ = Employer.objects.get_or_create(
            company_name=employer_name,
            defaults={
                'email': f"careers@{employer_name.replace(' ', '').lower()}.com",
                'website': f"https://{employer_name.replace(' ', '').lower()}.com",
                'is_verified': True,
                'trust_score': 90,
            },
        )
        created = now - timedelta(days=data.pop('days_ago'))
        Job.objects.get_or_create(
            title=data['title'],
            employer=employer,
            source='sample',
            defaults={
                **data,
                'source': 'sample',
                'status': 'approved',
                'is_featured': True,
                'expires_at': created + timedelta(days=30),
                'created_at': created,
            },
        )


def remove_sample_jobs(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')
    Employer = apps.get_model('jobs', 'Employer')
    Job.objects.filter(source='sample').delete()
    Employer.objects.filter(jobs__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_aggregationstate'),
    ]

    operations = [
        migrations.RunPython(seed_sample_jobs, remove_sample_jobs),
    ]
