# Generated by Django 6.0.6 on 2026-07-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="year_awarded",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="end_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="education",
            name="start_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="end_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="start_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="certification",
            name="date_awarded",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
