# Generated by Django 6.0.6 on 2026-07-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_remove_old_date_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True, help_text='Professional summary / About section for your portfolio'),
        ),
    ]
