# Generated by Django 6.0.6 on 2026-07-31 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_aggregationstate"),
        ("resumes", "0005_resume_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="job",
            field=models.ForeignKey(
                blank=True,
                help_text="Job this resume was created for",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resumes",
                to="jobs.job",
            ),
        ),
    ]
