# Generated by Django 6.0.6 on 2026-07-31 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0006_resume_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="is_paid",
            field=models.BooleanField(
                default=False, help_text="True when the one-time payment was completed"
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
