# Generated by Django 6.0.6 on 2026-07-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_city_userprofile_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="career_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Structured career biodata (education, experience, projects, certifications, languages) used to pre-fill job resumes.",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="skills",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated skills that will be auto-added to new job resumes.",
            ),
        ),
    ]
