# Generated by Django 6.0.6 on 2026-07-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0003_seed_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='archetype',
            field=models.CharField(blank=True, choices=[('A', 'Sidebar Left'), ('B', 'Header Banner'), ('C', 'Single Column'), ('D', 'Split Balanced'), ('E', 'Card/Panel'), ('F', 'Photo Forward')], help_text='Layout archetype (A-F) for new templates', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='ats_safe',
            field=models.BooleanField(default=True, help_text='Whether this template is ATS-friendly'),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='skin_file',
            field=models.CharField(blank=True, help_text='Path to the skin template (e.g., themes/skins/nebula.html)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='supports_monochrome',
            field=models.BooleanField(default=False, help_text='Whether this template supports monochrome mode'),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='supports_photo',
            field=models.BooleanField(default=False, help_text='Whether this template supports profile photos'),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='swatches',
            field=models.JSONField(blank=True, default=list, help_text='Preset accent colors as hex codes'),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags for filtering: modern, simple, with_photo, professional, ats'),
        ),
        migrations.AlterField(
            model_name='resumetemplate',
            name='html_file',
            field=models.CharField(help_text='Path to the template HTML file (for legacy templates)', max_length=200),
        ),
    ]
