from django.db import migrations


TEMPLATES = [
    {'name': 'Academic', 'description': 'Formal serif layout designed for researchers and academics. Emphasizes education, publications, and areas of expertise.', 'html_file': 'pdf/template_academic.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Aether', 'description': 'Sharp single column with structured underlines. Professional and precise for expert candidates.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'C', 'skin_file': 'skins/aether.html', 'tags': ['simple', 'ats', 'one_column'], 'swatches': ['#374151', '#6b7280', '#9ca3af'], 'supports_photo': False, 'supports_monochrome': True, 'ats_safe': True},
    {'name': 'Architect', 'description': 'Structured grid-like layout with slate sidebar and clean geometric feel. Precise spacing for architects and designers.', 'html_file': 'pdf/template_architect.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Astral', 'description': 'Tan photo header block with two-column body. Warm and professional for creative roles.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'E', 'skin_file': 'skins/astral.html', 'tags': ['modern', 'with_photo'], 'swatches': ['#d97706', '#f59e0b', '#b45309'], 'supports_photo': True, 'supports_monochrome': False, 'ats_safe': False},
    {'name': 'Astralis', 'description': 'Bold teal-bordered frame with dark sidebar. Striking and memorable for standout applications.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'A', 'skin_file': 'skins/astralis.html', 'tags': ['modern', 'with_photo'], 'swatches': ['#e94560', '#dc2626', '#f43f5e'], 'supports_photo': True, 'supports_monochrome': False, 'ats_safe': False},
    {'name': 'Aurora', 'description': 'Rose-toned panels with card-per-section layout. Unique and distinctive for creative professionals.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'E', 'skin_file': 'skins/aurora.html', 'tags': ['modern', 'creative'], 'swatches': ['#ec4899', '#db2777', '#be185d'], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': False},
    {'name': 'Axis', 'description': 'High-contrast blue sidebar with bold uppercase name. Strong visual hierarchy for leadership roles.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'A', 'skin_file': 'skins/axis.html', 'tags': ['modern', 'with_photo'], 'swatches': ['#1d4ed8', '#2563eb', '#3b82f6'], 'supports_photo': True, 'supports_monochrome': False, 'ats_safe': False},
    {'name': 'Bold', 'description': 'Heavy typography with strong contrast and amber accents. Thick colored left borders on sections make a powerful visual statement.', 'html_file': 'pdf/template_bold.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Celestial', 'description': 'Soft neutral tones with refined serif typography. Two even columns for balanced presentation.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'D', 'skin_file': 'skins/celestial.html', 'tags': ['simple', 'two_column', 'ats'], 'swatches': ['#374151', '#6b7280', '#9ca3af'], 'supports_photo': False, 'supports_monochrome': True, 'ats_safe': True},
    {'name': 'Classic', 'description': 'A clean, traditional single-column layout with serif typography. ATS-friendly and perfect for formal industries like finance, law, and government.', 'html_file': 'pdf/template_classic.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Classic Europass', 'description': 'A clean, traditional sidebar layout with light-blue panel. ATS-friendly and perfect for formal industries.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'A', 'skin_file': 'skins/classic-europass.html', 'tags': ['simple', 'ats', 'professional', 'with_photo'], 'swatches': ['#1a5276', '#2e86c1', '#1e3a5f'], 'supports_photo': True, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Comet', 'description': 'Vibrant yellow header with black pill-shaped detail boxes. Eye-catching and dynamic.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'B', 'skin_file': 'skins/comet.html', 'tags': ['modern', 'with_photo'], 'swatches': ['#fbbf24', '#f59e0b', '#d97706'], 'supports_photo': True, 'supports_monochrome': False, 'ats_safe': False},
    {'name': 'Compact', 'description': 'A dense two-column layout optimized for candidates with extensive experience. Fits more content on a single page.', 'html_file': 'pdf/template_compact.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Consultant', 'description': 'Professional indigo scheme with skill progress bars and achievement-focused formatting. Results-driven layout for consultants.', 'html_file': 'pdf/template_consultant.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Corporate', 'description': 'Professional blue and gray color scheme with structured corporate lines. A polished, business-ready layout for established professionals.', 'html_file': 'pdf/template_corporate.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Cosmos', 'description': 'Grey photo header banner with broad career overview. Comprehensive and professional.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'E', 'skin_file': 'skins/cosmos.html', 'tags': ['modern', 'with_photo'], 'swatches': ['#6b7280', '#9ca3af', '#d1d5db'], 'supports_photo': True, 'supports_monochrome': True, 'ats_safe': False},
    {'name': 'Creative', 'description': 'A colorful coral sidebar with contact info, skills, and languages. The main area showcases experience and education. Perfect for creative roles.', 'html_file': 'pdf/template_creative.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Designer', 'description': 'Creative two-column layout with dark sidebar for skills and contact. Colorful skill tags and a portfolio-style presentation.', 'html_file': 'pdf/template_designer.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Eclipse', 'description': 'Centered header with generous whitespace. Monochrome-only for a minimalist, sophisticated look.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'C', 'skin_file': 'skins/eclipse.html', 'tags': ['simple', 'ats', 'one_column'], 'swatches': ['#6b7280', '#9ca3af', '#d1d5db'], 'supports_photo': False, 'supports_monochrome': True, 'ats_safe': True},
    {'name': 'Elegant', 'description': 'Refined design with italic serif name, burgundy color scheme, and decorative dividers. A classic sophisticated look for any profession.', 'html_file': 'pdf/template_elegant.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Engineer', 'description': 'Technical structured look with orange accents and monospace elements. Grid-based skills with bracket styling for engineers.', 'html_file': 'pdf/template_engineer.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Eon', 'description': 'Small photo beside name in dense single column. Clean and easy-to-read for qualifications focus.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'F', 'skin_file': 'skins/eon.html', 'tags': ['simple', 'ats', 'with_photo'], 'swatches': ['#1f2937', '#374151', '#6b7280'], 'supports_photo': True, 'supports_monochrome': True, 'ats_safe': True},
    {'name': 'Executive', 'description': 'Dark navy header with gold accents and serif typography. A formal, traditional layout for senior professionals and executives.', 'html_file': 'pdf/template_executive.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Executive', 'description': 'Compact single-line header with dot markers. ATS-safe plain formatting for senior professionals.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'C', 'skin_file': 'skins/executive.html', 'tags': ['professional', 'ats', 'simple'], 'swatches': ['#1f2937', '#374151', '#6b7280'], 'supports_photo': False, 'supports_monochrome': True, 'ats_safe': True},
    {'name': 'Exoplanet', 'description': 'Simple single column with two-column skills list. Organized and neat for clear presentation.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'C', 'skin_file': 'skins/exoplanet.html', 'tags': ['simple', 'ats', 'one_column'], 'swatches': ['#374151', '#6b7280', '#9ca3af'], 'supports_photo': False, 'supports_monochrome': True, 'ats_safe': True},
    {'name': 'Finance', 'description': 'Conservative dark blue with yellow accent bar and percentage-based skill bars. A numbers-focused layout for finance professionals.', 'html_file': 'pdf/template_finance.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Flat', 'description': 'Ultra-modern flat design with solid blue header bars, skill progress bars, and chip-style languages. Minimal and contemporary.', 'html_file': 'pdf/template_flat.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Galaxy', 'description': 'Centered name with dotted leader lines pushing dates to the right edge. Classic and elegant.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'C', 'skin_file': 'skins/galaxy.html', 'tags': ['simple', 'ats', 'professional'], 'swatches': ['#111827', '#374151', '#6b7280'], 'supports_photo': False, 'supports_monochrome': True, 'ats_safe': True},
    {'name': 'Graduate', 'description': 'Designed for fresh graduates with education section prominent at top. Clean layout with blue accents, ideal for internships and entry-level.', 'html_file': 'pdf/template_graduate.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Helix', 'description': 'Circular profile photo top-left with two-column layout. Generous whitespace and minimal rules.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'D', 'skin_file': 'skins/helix.html', 'tags': ['modern', 'with_photo', 'two_column'], 'swatches': ['#059669', '#10b981', '#34d399'], 'supports_photo': True, 'supports_monochrome': False, 'ats_safe': False},
    {'name': 'Horizon', 'description': 'Bold black outer border frame with traditional serif layout. Formal and distinctive.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'F', 'skin_file': 'skins/horizon.html', 'tags': ['professional', 'with_photo'], 'swatches': ['#1f2937', '#374151', '#6b7280'], 'supports_photo': True, 'supports_monochrome': True, 'ats_safe': False},
    {'name': 'Hyperion', 'description': 'Grey pill-shaped date badges above job entries. Clean and organized for experienced professionals.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'C', 'skin_file': 'skins/executive.html', 'tags': ['simple', 'ats', 'one_column'], 'swatches': ['#374151', '#6b7280', '#9ca3af'], 'supports_photo': False, 'supports_monochrome': True, 'ats_safe': True},
    {'name': 'Journalist', 'description': 'Editorial newspaper feel with black, white, and red accents. Serif headlines and dateline-style dates for media professionals.', 'html_file': 'pdf/template_journalist.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Keystone', 'description': 'Soft pale-blue sidebar with teal accent line. Professional and approachable for mid-career professionals.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'A', 'skin_file': 'skins/keystone.html', 'tags': ['modern', 'with_photo'], 'swatches': ['#0369a1', '#0ea5e9', '#38bdf8'], 'supports_photo': True, 'supports_monochrome': False, 'ats_safe': False},
    {'name': 'Lawyer', 'description': 'Very formal dark charcoal with serif typography and traditional layout. Conservative professional look for legal professionals.', 'html_file': 'pdf/template_lawyer.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Lunar', 'description': 'Slim left info rail with monochrome dial. Minimalist and elegant for clarity-focused candidates.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'A', 'skin_file': 'skins/lunar.html', 'tags': ['simple', 'ats', 'with_photo'], 'swatches': ['#334155', '#475569', '#64748b'], 'supports_photo': True, 'supports_monochrome': True, 'ats_safe': True},
    {'name': 'Marketing', 'description': 'Bold colorful design with magenta accents and colored section backgrounds. Dynamic skill bars and chip-style languages.', 'html_file': 'pdf/template_marketing.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Medical', 'description': 'Clean clinical white with teal accents. Professional medical look with clear sections for certifications and clinical qualifications.', 'html_file': 'pdf/template_medical.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Meteor', 'description': 'Vibrant and innovative template for creative, forward-thinking career paths.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'B', 'skin_file': 'skins/comet.html', 'tags': ['modern', 'creative', 'with_photo'], 'swatches': ['#f97316', '#ea580c', '#c2410c'], 'supports_photo': True, 'supports_monochrome': False, 'ats_safe': False},
    {'name': 'Minimalist', 'description': 'Ultra-clean design with generous whitespace, thin dividers, and light gray section headers. Lets your content speak for itself.', 'html_file': 'pdf/template_minimalist.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Modern', 'description': 'A two-column layout with a dark sidebar for skills, languages, and certifications. Great for tech, creative, and startup roles.', 'html_file': 'pdf/template_modern.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Modern Clean', 'description': 'A sleek, modern template with indigo gradient header and two-column body. Great for tech and creative roles.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'B', 'skin_file': 'skins/modern-clean.html', 'tags': ['modern', 'with_photo', 'two_column'], 'swatches': ['#4f46e5', '#7c3aed', '#2563eb'], 'supports_photo': True, 'supports_monochrome': False, 'ats_safe': False},
    {'name': 'Nebula', 'description': 'Solid blue header with sidebar-style education and skills. Creative and expansive for diverse skills.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'A', 'skin_file': 'skins/nebula.html', 'tags': ['modern', 'with_photo'], 'swatches': ['#1e40af', '#2563eb', '#3b82f6'], 'supports_photo': True, 'supports_monochrome': False, 'ats_safe': False},
    {'name': 'Nebular', 'description': 'Cream sidebar panel with warm tones. Contemporary and visually appealing for personal branding.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'A', 'skin_file': 'skins/nebular.html', 'tags': ['modern', 'with_photo'], 'swatches': ['#8b5a2b', '#d4a574', '#a0522d'], 'supports_photo': True, 'supports_monochrome': False, 'ats_safe': False},
    {'name': 'Nova', 'description': 'Bright pale-green header with arrow accents. Bold and transformative for career moments.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'B', 'skin_file': 'skins/nova.html', 'tags': ['modern', 'one_column'], 'swatches': ['#22c55e', '#16a34a', '#15803d'], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': False},
    {'name': 'Orbit', 'description': 'Left-aligned plain header with tight line spacing. Clean and efficient for experienced professionals.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'C', 'skin_file': 'skins/orbit.html', 'tags': ['simple', 'ats', 'one_column'], 'swatches': ['#111827', '#374151', '#6b7280'], 'supports_photo': False, 'supports_monochrome': True, 'ats_safe': True},
    {'name': 'Photographer', 'description': 'Visual-first layout with dark header and warm amber accents. Portfolio-style description formatting for visual artists and photographers.', 'html_file': 'pdf/template_photographer.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Professional', 'description': 'A clean, traditional resume layout with serif fonts and a formal structure. Best for corporate, finance, and academic positions.', 'html_file': 'pdf/resume_professional.html', 'is_active': True, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Professional Sidebar', 'description': 'Slim dark header with photo, single flowing column. Professional and polished for established careers.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'B', 'skin_file': 'skins/professional-sidebar.html', 'tags': ['modern', 'with_photo', 'professional'], 'swatches': ['#1e293b', '#334155', '#475569'], 'supports_photo': True, 'supports_monochrome': True, 'ats_safe': True},
    {'name': 'Pulsar', 'description': 'Pale green sidebar with arrow accents. Fresh and modern for growth-oriented professionals.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'A', 'skin_file': 'skins/pulsar.html', 'tags': ['modern', 'with_photo'], 'swatches': ['#16a34a', '#22c55e', '#059669'], 'supports_photo': True, 'supports_monochrome': False, 'ats_safe': False},
    {'name': 'Quantum', 'description': 'Thin solid navy top bar with right-aligned contact details. Split-column body for balanced presentation.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'D', 'skin_file': 'skins/quantum.html', 'tags': ['modern', 'with_photo', 'two_column'], 'swatches': ['#1e3a5f', '#2563eb', '#3b82f6'], 'supports_photo': True, 'supports_monochrome': False, 'ats_safe': False},
    {'name': 'Quasar', 'description': 'Muted grey tones with two-column skills grid. Understated and professional for technical roles.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'C', 'skin_file': 'skins/quasar.html', 'tags': ['simple', 'ats', 'one_column'], 'swatches': ['#4b5563', '#6b7280', '#9ca3af'], 'supports_photo': False, 'supports_monochrome': True, 'ats_safe': True},
    {'name': 'Researcher', 'description': 'Modern academic design with deep purple accents. Publications-friendly with pill-style skills and clear research hierarchy.', 'html_file': 'pdf/template_researcher.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Shokumukeirekisho', 'description': 'Detailed career history template designed to highlight experience and achievements.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'C', 'skin_file': 'skins/galaxy.html', 'tags': ['professional', 'ats', 'one_column'], 'swatches': ['#1f2937', '#374151', '#4b5563'], 'supports_photo': False, 'supports_monochrome': True, 'ats_safe': True},
    {'name': 'Solstice', 'description': 'Bold name with thick double horizontal rule. Strong visual impact for confident candidates.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'C', 'skin_file': 'skins/solstice.html', 'tags': ['modern', 'ats', 'one_column'], 'swatches': ['#111827', '#1f2937', '#374151'], 'supports_photo': False, 'supports_monochrome': True, 'ats_safe': True},
    {'name': 'Starburst', 'description': 'Dark charcoal header bar with photo and two-column body. Modern and professional.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'B', 'skin_file': 'skins/starburst.html', 'tags': ['modern', 'with_photo', 'two_column'], 'swatches': ['#1f2937', '#374151', '#6b7280'], 'supports_photo': True, 'supports_monochrome': True, 'ats_safe': False},
    {'name': 'Startup', 'description': 'Modern casual feel with green accents and dashed dividers. Pill-style skills and an approachable design for the startup ecosystem.', 'html_file': 'pdf/template_startup.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Stellar', 'description': 'Two-column with icon-prefixed contact details. Sleek and polished for standout achievements.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'F', 'skin_file': 'skins/stellar.html', 'tags': ['simple', 'ats', 'one_column'], 'swatches': ['#6b7280', '#9ca3af', '#d1d5db'], 'supports_photo': False, 'supports_monochrome': True, 'ats_safe': True},
    {'name': 'Swiss', 'description': 'Grid-based minimalist design inspired by Swiss typography. Clean two-column layout with red accent and strong typographic hierarchy.', 'html_file': 'pdf/template_swiss.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Tech', 'description': 'Dark-themed with monospace fonts and teal accents. Features code-style section headers and tag-based skills. Built for developers and engineers.', 'html_file': 'pdf/template_tech.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Two-Column Balanced', 'description': 'Equal-width columns with diamond bullets and clean dividers. Balanced and professional.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'D', 'skin_file': 'skins/two-column-balanced.html', 'tags': ['modern', 'two_column'], 'swatches': ['#1e40af', '#2563eb', '#3b82f6'], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Writer', 'description': 'Typography-focused editorial design with Georgia serif, warm brown accents, and a literary feel. Perfect for writers and editors.', 'html_file': 'pdf/template_writer.html', 'is_active': False, 'archetype': None, 'skin_file': None, 'tags': [], 'swatches': [], 'supports_photo': False, 'supports_monochrome': False, 'ats_safe': True},
    {'name': 'Zenith', 'description': 'Soft pastel-green sidebar with bold section bars. Minimalistic with clarity and impact.', 'html_file': 'pdf/resume_pdf.html', 'is_active': True, 'archetype': 'A', 'skin_file': 'skins/zenith.html', 'tags': ['modern', 'with_photo'], 'swatches': ['#22c55e', '#16a34a', '#15803d'], 'supports_photo': True, 'supports_monochrome': False, 'ats_safe': False},
]


def seed_full_catalog(apps, schema_editor):
    ResumeTemplate = apps.get_model('templates_app', 'ResumeTemplate')
    ResumeTemplate.objects.filter(html_file__in=[
        'pdf/resume_professional.html',
        'pdf/resume_modern.html',
        'pdf/resume_creative.html',
    ]).delete()
    for data in TEMPLATES:
        name = data.pop("name")
        html_file = data.pop("html_file")
        ResumeTemplate.objects.update_or_create(name=name, html_file=html_file, defaults=data)


def remove_full_catalog(apps, schema_editor):
    ResumeTemplate = apps.get_model('templates_app', 'ResumeTemplate')
    ResumeTemplate.objects.filter(name__in=[d["name"] for d in TEMPLATES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0004_add_template_theming_fields'),
    ]

    operations = [
        migrations.RunPython(seed_full_catalog, remove_full_catalog),
    ]
