# Generated by Django 6.0.6 on 2026-07-31 11:35

from django.db import migrations, models


def strip_ats_tags(apps, schema_editor):
    ResumeTemplate = apps.get_model('templates_app', 'ResumeTemplate')
    for template in ResumeTemplate.objects.exclude(tags=[]):
        tags = [t for t in (template.tags or []) if t != 'ats']
        if tags != template.tags:
            template.tags = tags
            template.save(update_fields=['tags'])


class Migration(migrations.Migration):

    dependencies = [
        ("templates_app", "0005_seed_full_catalog"),
    ]

    operations = [
        migrations.RunPython(strip_ats_tags, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="resumetemplate",
            name="ats_safe",
        ),
        migrations.AlterField(
            model_name="resumetemplate",
            name="tags",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Tags for filtering: modern, simple, with_photo, professional",
            ),
        ),
    ]
