# Generated by Django 6.0.6 on 2026-07-30 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_match', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillgapanalysis',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gap_analyses', to='resumes.resume'),
        ),
    ]
