# Generated by Django 6.0.6 on 2026-07-31 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_match', '0003_analysistask'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgapanalysis',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='job_match.analysistask'),
        ),
    ]
