# Generated by Django 6.0.6 on 2026-07-31 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_match', '0004_skillgapanalysis_task'),
        ('resumes', '0005_resume_summary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='JobPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(blank=True, db_index=True, help_text='SHA-1 of resume text (for uploaded files)', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobs', models.ManyToManyField(blank=True, related_name='pools', to='job_match.jobdescription')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_pools', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_pools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Pool',
                'verbose_name_plural': 'Job Pools',
                'ordering': ['-updated_at'],
            },
        ),
    ]
