# Generated by Django 6.0.6 on 2026-07-30 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='qr_code',
        ),
    ]
